### ISSUE TITLE
cell-wise processing

### ISSUE THREAD

**Issue by johncolby** [fastai/fastai-nbstripout#1]
It would be nice to be able to enable/disable the processing on a cell-wise basis, like the other version of nbstripout. I presume this is already planned, but if not, just thought I would suggest it. Thanks for sharing!

**Comment by stas00** [comment]
I'm appreciating your PR, @johncolby, as it tells me that I didn't communicate clearly what this repo is for.

I updated README to indicate that this is as-is software at the moment and isn't trying to replicate the full nbstripout functionality. 

But you're welcome to fork it and make another version that is fully compatible with the original, @johncolby.
